### ISSUE TITLE
iOS Swift 403 issue in Xcode and crashes

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-server#1600]
Check out [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an ideal bug report. The closer your issue report is to that one, the more likely we are to be able to help, and the more likely we will be to fix the issue quickly!

For implementation related questions or technical support, please refer to the [Stack Overflow](http://stackoverflow.com/questions/tagged/parse.com) and [Server Fault](https://serverfault.com/tags/parse) communities.

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x ] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse Server running on Heroku

swift code added to AppDelegate.swift

```
    Parse.initializeWithConfiguration(ParseClientConfiguration(block: { (configuration: ParseMutableClientConfiguration) -> Void in
        configuration.server = "https://xxx.herokuapp.com/parse/" // '/' important after 'parse'
        configuration.applicationId = "xxxxx"
        configuration.clientKey = "xxx"
    }))
```

Code taken from Parse Server Example, and not clear if you need client key since it says its optional on the parse server git readme.  (we need some clarification)

When running the code I see at the bottom of xcode 

```
2016-04-22 12:47:00.940 xxx[8414:4911444] [Error]: Response status code was unacceptable: 403 (Code: 1, Version: 1.13.0)
fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb) 
```

**Comment by drew-gross** [comment]
Could you provide some server logs from when you make this request?

**Comment by gateway** [comment]
I believe the issue is with images, its returning null, or 403.

Setup is Heroku running parse server 2.2.7, running the latest dashboard also on heroku, data was migrated to mlab.  When clicking a link to a photo/image in the dashboard we get the aws access denied.

**Comment by drew-gross** [comment]
Send me your email address and I'll add you to the slack

**Comment by gateway** [comment]
done

**Comment by gateway** [comment]
Ok this took a bit to dig around and find what the issue was.

Things learned.

If you use profileImages and make a build on parse.com then build your own parse server, your iOS build will have a reference image link to parse.com which would fail.  The file url was invalid which caused it to crash.

If your not refreshing your user profile at launch (we do it ever so often) and go from parse.com to your own parse server this could happen to you, its easy to resolve, delete the app off your phone and rebuild it.

Another thing is make sure your fileKey is set on the parse server, if you don't you will get access denied.

cheers to @nlutsenko for helping me debug this..

**Comment by kanersan** [comment]
@gateway 
I'm having this exact same issue and I have similar configuration to yours. Heroku and mlab for server and db. 

And my files are being served from S3 - AWS. Some images load fine but some don't. 
I tried deleting the app but that didn't resolve the issue. I still get 403 for only some images. Any help would be appreciated.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
