### ISSUE TITLE
Windows 8

### ISSUE THREAD

**Issue by manishmalani** [ParsePlatform/parse-server#3066]
We were using Parse.com in production and now migrated to hosted parse server.
I know as of now parse server does not support windows 8 push notifications.
Any guidance to make it work will be much appreciated. 

Thanks in advance!

**Comment by tetreault** [comment]
Hello @manishmalani where did you read this? I have been told otherwise by some MSFT reps who are catering to us to use the Microsoft Azure Parse service. I, however, don't have my app ported over and working yet. I will be very disappointed if this is the case... Windows Phone 8 seems to totally be an afterthought by Microsoft and hasn't proven to be very developer friendly at all. 

Here's my article I'm referencing: https://azure.microsoft.com/en-us/blog/announcing-the-publication-of-parse-server-with-azure-managed-services/

**Comment by manishmalani** [comment]
Thanks @tetreault for your response and input. 

Following wiki says only about APNS (iOS) and GCM (Android) installation on Parse server. https://github.com/ParsePlatform/parse-server/wiki/Push and under ‘Future Improvements’ topic  its mention that they will ‘support more platforms’ in future.

This is the base of my assumption that Parse server do not support windows.

We have deployed parse server on our in-house machine and organization do not intend to use paid services like Azure. For iOS and Android we got it working.

**Comment by hramos** [comment]
Support for Windows Phone push hasn't been added yet as far as I know. If this is something you really need and using other third party services won't fit your needs, feel free to submit a PR to add a Windows push adapter.

Closing as this is not about any specific bug.

**Comment by tetreault** [comment]
@hramos 

So the original Parse SDK did support Windows Phone 8 (since we have it working still on Windows Phone 8). But the Parse Server implementation has removed any Windows Phone 8 documentation? 

This is confusing, could you help clarify this for us? We understand that we are on our own when it comes to hosting Parse, but we have been directed to use Parse Server hosted on a service like Azure but Parse Server doesn't include WP8 support but the original Parse .NET SDK does? This seems segmented and confusing. Any light you can shed on this is appreciated.

**Comment by hramos** [comment]
You still use the same SDKs when using Parse.com or Parse Server, they still have the same support for receiving push notifications.

Parse Server is a re-implementation of the Parse.com hosted service, meant to run on your own infra for a single Parse app, and in its initial release it did not include WP8 push notification support. There's nothing preventing anyone from adding support for this to Parse Server, however.
