### ISSUE TITLE
Schema mismatch for _Session.createdWith

### ISSUE THREAD

**Issue by nirco123** [ParsePlatform/parse-server#32]
When I am trying to login using the local parse-server and migrated mongoDB (on MongoLab), I am getting the following:
{"code":111,"error":"schema mismatch for _Session.createdWith; expected map but got object"}

please advice.

**Comment by jsoendermann** [comment]
I get the same error.

**Comment by rebelchris** [comment]
Subscribing: Same here

**Comment by fraxool** [comment]
Same here with iOs SDK.

**Comment by gfosco** [comment]
Will take a look at this.

**Comment by hafizapp** [comment]
Yes same here for, iOS app, any one have luck to get it working...

**Comment by hmoqhim** [comment]
Same thing here.

**Comment by poseidonsw** [comment]
I'm getting the same error using the JS SDK

**Comment by natanrolnik** [comment]
I've just deployed the parse server for my app, and when trying to login or create a new user account (iOS SDK), I'm getting the same error.

**Comment by gfosco** [comment]
Can you open the _SCHEMA collection in your mongo installation, and paste the value for the _Session object?

**Comment by poseidonsw** [comment]
@gfosco this was mine right out of the migrate tool before I made the changes I posted above.

    {
    "_id" : "_Session",
    "_metadata" : {
        "class_permissions" : {
            "get" : {
                "*" : true
            },
            "find" : {
                "*" : true
            },
            "update" : {
                "*" : true
            },
            "create" : {
                "*" : true
            },
            "delete" : {
                "*" : true
            },
            "addField" : {
                "*" : true
            },
            "readUserFields" : [],
            "writeUserFields" : []
        }
    },
    "user" : "*_User",
    "installationId" : "string",
    "restricted" : "boolean",
    "expiresAt" : "date",
    "createdWith" : "map",
    "sessionToken" : "string",
    "updatedAt" : "string",
    "createdAt" : "string",
    "objectId" : "string"
}

**Comment by gfosco** [comment]
Merged #87 which should address all of this.  Will tag a new release. 2.0.2

**Comment by vection** [comment]
Hi Fosco,
the recent changes have not solved the problem for me. Still getting `schema mismatch for _Session.createdWith; expected map but got object` as a response to a login. I have upgraded to 2.0.2 on my Heroku instance using the MongoLab MongoDB as described in the migration guide.
Other GET requests for example get through as expected though.

**Comment by natanrolnik** [comment]
@vection take a look at @poseidonsw first comment. There may be a bug in the migration tool, and in the _Session schema you need to change:

```
"createdWith": "object"
```

from a `map` to an `object`.
Also, I needed to change the `expiresAt` field from `date` to `string` in order for this to work.

**Comment by gfosco** [comment]
Caught that in #87 just now...  can you try the current master?

**Comment by vection** [comment]
Yes, I already tested it with the current master (2.0.2).
Doing the changes to _SCHEMA:_session (change `createdWith` value to `object` and `expiresAt` value to `string`) worked however.

**Comment by poseidonsw** [comment]
@gfosco I can clean up my change for expiresAt and send it as a PR.  It sets the expiresAt a year in advance similar to what parse.com api does.  You do still need to change it in the _SCHEMA:_Session from date to string, but that would make it consistent with the other dates in the _SCHEMA collection

**Comment by jpv123** [comment]
I'm sorry, I don't understand. Was it solved on 2.0.2? I'm having also the same problem

**Comment by gfosco** [comment]
Should be in 2.0.3

**Comment by hafizapp** [comment]
Till now it's same thing, please fix ..

[Error]: schema mismatch for _Session.expiresAt; expected date but got string (Code: 111, Version: 1.12.0)

@gfosco

**Comment by natanrolnik** [comment]
@hafizapp to fix date, open your schema in your mongodb, and find the `_Session` object. There, you should change expiresAt from `date` to `String`.

**Comment by gfosco** [comment]
Yeah, that will fix it, but we do need to add something in parse-server to
handle this scenario cleanly without having to edit the schema.

**Comment by fraxool** [comment]
@gfosco should we wait for the fix or can we change the expiresAt from `date` to `string` now and continue the development from here ? I mean, if we change the mongodb shema, will we have some issues with the next updates of parse-server ?

**Comment by hafizapp** [comment]
@natanrolnik Thanks, It fixed. but if would be more helpful if we get the answer of @fraxool  question.

**Comment by natanrolnik** [comment]
@hafizapp definitely

**Comment by rebelchris** [comment]
I did change to 2.0.3 and changed expiresAt from date to string 

It seems to work, but the js sdk gives me the following error:
Uncaught Error: Tried to encode an unsaved file.

File  parse-1.6.7.min.js:9164
I'm guessing it has something to do with this issue? since it was working before..

**Comment by joeyslack** [comment]
I'm getting issues with expiredAt. Is it still valid for me to change my schema, to convert expiresAt from Date type (iso) to String?

**Comment by drew-gross** [comment]
Sure, but I'd recommend you try that on a dev DB before doing it in your prod DB. Can you also open a new issue describing how you got into this situation? (Was this a migrated DB, or a new one? Does your app use revocable sessions? etc.)

**Comment by chrisco314** [comment]
I hope I am not hijacking this thread, but I seem to have missed a significant memo.  I first tried to migrate & run an existing parse app and Mongo instance on my dev machine, and that seemed to mostly work, except for authentication.  

The app that I inherited had a simple / default authentication model.  To migrate the data to my local Mongo instance, I exported the data and then used `mongoimport` for each collection file.  That mostly worked, but I am at a loss to understand how to authenticate users (previously I could test this via curl:

    curl -X GET \
      -H "X-Parse-Application-Id: $PARSE_APP_ID" \
      -H "X-Parse-REST-API-Key: $PARSE_REST_KEY" \
      -H "X-Parse-Revocable-Session: 1" \
      -G \
      --data-urlencode username='username' \
      --data-urlencode password='user_password' \
      https://api.parse.com/1/login | python -m json.tool

From what I can tell though, there is no end point for that.  What I am I missing on the authentication model?  Is running the app locally significantly different than running it on a hosting service?

Many Thanks.
